name: Deploy S3 Bucket

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 's3-bucket.yaml'
      - '.github/workflows/main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    env:
      AWS_REGION: ${{ secrets.AWS_REGION || 'ap-south-1' }}
      BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check AWS Credentials
        run: |
          echo "Access Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "Secret Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"  
          echo "Secret Key: ${{ secrets.AWS_REGION }}"
          echo "Secret Key: ${{ secrets.S3_BUCKET_NAME }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://s3-bucket.yaml

      - name: Verify AWS Login
        run: |
          aws sts get-caller-identity

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --stack-name s3-bucket-stack \
            --template-file s3-bucket.yaml \
            --parameter-overrides BucketName=${{ env.BUCKET_NAME }} EnableVersioning=true BlockPublicAccess=true \
            --capabilities CAPABILITY_NAMED_IAM

      